name: Build Offline APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 步骤1：准备网页资源
      - name: Prepare Web Assets
        run: |
          mkdir -p android/app/src/main/assets/www/
          cp -R web/* android/app/src/main/assets/www/

      # 步骤2：设置JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 步骤3：构建APK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run Gradle Build
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      # 步骤4：上传APK（使用v4版本）
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: offline-app
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 7  # 自动7天后删除产物
