name: Build Offline APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 步骤1：设置JDK 17（必须）
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # 关键修改点
          distribution: 'temurin'

      # 步骤2：准备网页资源
      - name: Prepare Web Assets
        run: |
          mkdir -p android/app/src/main/assets/www/
          cp -R web/* android/app/src/main/assets/www/

      # 步骤3：设置Android SDK（跳过JDK版本检查）
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        env:
          SKIP_JDK_VERSION_CHECK: true  # 关键修复

      # 步骤4：构建APK
      - name: Run Gradle Build
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      # 步骤5：上传APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: offline-app
          path: android/app/build/outputs/apk/release/*.apk
